Add Docker detection rules

diff --git a/dvim b/dvim
--- a/dvim
+++ b/dvim
@@ -2,4 +2,14 @@
 
 set -e
 
+hash docker &>/dev/null || {
+  echo "Could not find Docker. Please install Docker first."
+  exit 1
+}
+
+groups | grep docker &>/dev/null || {
+  echo "You are not permitted to run Docker. Please run \`sudo usermod -aG docker $USER\` first."
+  exit 1
+}
+
 docker run --rm -it -u $UID -e "HOME=$HOME" -v "$HOME:$HOME" -v "/etc/passwd:/etc/passwd:ro" -v "/etc/shadow:/etc/shadow:ro" -v "/etc/group:/etc/group:ro" -v "/etc/sudoers.d:/etc/sudoers.d:ro" -v "$PWD:$PWD" -w "$PWD" bcbcarl/vim $@
